### ISSUE TITLE
breaking permaprops

### ISSUE THREAD

**Issue by Aws0mee** [NanoAi/gm_apg#33]
This addon seems to be breaking the permaprops tool. Since you can't physgun permaprops it won't let you remove it.

[ERROR] addons/permaprops/lua/permaprops/sv_lib.lua:195: attempt to index local 'trace' (a nil value)
  1. CanTool - addons/permaprops/lua/permaprops/sv_lib.lua:195
   2. CanTool - gamemodes/darkrp/gamemode/modules/fpp/pp/server/core.lua:478
    3. canTool - gamemodes/darkrp/gamemode/modules/fpp/pp/sh_cppi.lua:70
     4. func - addons/gm_apg-master/lua/apg/modules/tools.lua:35
      5. Call - addons/sam-1.2.7/lua/includes/modules/hook.lua:16
       6. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:261

**Comment by AvarianKnight** [comment]
I don't believe this is an issue with APG. If you are a superadmin you can physgun permaprops, and the only time APG blocks you with the CanTool (the one cited in the trace) is if it has ToolDisabled on the entity, or if the player can't pickup an entity (most likely because they tried to abuse stacks).
