### ISSUE TITLE
Breaks color tool, other addons using canpickup hook and light/lamp

### ISSUE THREAD

**Issue by Synkstar** [NanoAi/gm_apg#39]
I was testing it with patch protect and it breaks the can pickup

**Comment by AvarianKnight** [comment]
The color tool can be fixed by disabling Enable Color under ghosting, it is expected that it overrides canpickup hooks because if the player has abused props they will be locked out of their Physgun for a designated amount of time. You'll have to give me a video for the light/lamps because they work fine for me.

**Comment by Synkstar** [comment]
Sorry forgot about this I fixed them both by doing that....

**Comment by AvarianKnight** [comment]
👍
