### ISSUE TITLE
Question about allowing damage from world items

### ISSUE THREAD

**Issue by EwDirt** [NanoAi/gm_apg#9]
I have a func_door and func_tracktrain in my map that I want to do damage to players. APG appears to stop players receiving damage from world brushes.

Where would I go in the files to enable them again?

**Comment by sarahsturgeon** [comment]
In the server console you can do;

```lua
hook.Remove("EntityTakeDamage", "APG_noPropDmg")
```

and it'll stop the anti-prop-damage for that session.

Otherwise you can delete/comment out this section: https://github.com/NanoAi/gm_apg/blob/983d5b35ccfbacfaa5424ec5051e406adb92282c/lua/apg/modules/misc.lua#L47-L58

Good luck!

**Comment by NanoAi** [comment]
Or you can set AllowPK to be on.

**Comment by NanoAi** [comment]
But yeah it's a bit of an oversight on my end. ^^;

**Comment by NanoAi** [comment]
Are you willing to do some hacking with your brushes? Because there's a
sure fire way to get gmod and most mods to respect them as part of the
world. It's odd that it thinks they aren't imo. (Check if they return as world objects first.)

**Comment by sarahsturgeon** [comment]
Haha yeah and of course the config.

**Comment by NanoAi** [comment]
The thing is that because of how the physics engine works I have to block the `DMG_CRUSH` or else people would be able to head smash players into the floor and kill them via world. 

This makes the issue basically unsolvable, and the only way you can get around it is by either editing the file to allow `DMG_CRUSH` by removing this code `dmg:GetDamageType() == DMG_CRUSH or` or by setting AllowPK to be on...
